#version 450

layout(binding = 0, rgba32f) uniform writeonly image3D Data;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 8) in;
void main() 
{
	ivec3 size = imageSize(Data).xyz;

	if (gl_GlobalInvocationID.x < size.x && gl_GlobalInvocationID.y < size.y && gl_GlobalInvocationID.z < size.z)
	{
		vec4 p = 1e8f.xxxx;
		p.w = uintBitsToFloat(0);

		imageStore(Data, ivec3(gl_GlobalInvocationID), p);
	}
}
